#!/usr/bin/env bash
# installing NGIINX on my server

# updating pacckages
sudo apt-get -y update

# installing nginx
sudo apt-get install -y nginx

# costom html file with hello wworld
echo 'Hello Worldi!' > /var/www/html/index.nginx-debian.html

# Ensure nginx is not usinf systemd for restarting (using service cmd instead)
sudo service nginx start
