#!/usr/bin/env bash
# installing NGIINX on my server

# updating pacckages
sudo apt-get update

# installing nginx
sudo apt-get install -y nginx

# costom html file with hello wworld
echo "Hello World!" > /var/www/html/index.enginx-debian.html

# Ensure nginx is not usinf systemd for restarting (using service cmd instead)
service nginx start
