#!/usr/bin/env bash
# installing NGINX on my server

# updating packages
sudo apt-get -y update

# installing nginx
sudo apt-get -y install nginx

# custom html file with hello world
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Ensure nginx is not using systemd for restarting (using service cmd instead)
sudo service nginx start

# Use sed to add a location block for /redirect_me with a 301 redirection
sudo sed -i '/^}/i \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes using service command
sudo service nginx restart

# Ensure Nginx is running
sudo nginx -s reload
