#!/usr/bin/env bash
# add_header x-served-By

# updating pacckages
# sudo apt-get -y update

# installing nginx
# sudo apt-get -y install nginx

# Modify the Nginx configuration file to add custom header in the server block
sudo sed -i '/http {/a\		add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# restart nginx to apply changes 
sudo systemctl restart nginx.service
