#!/usr/bin/env bash
# the script generates a MySQL dump and creates and creates a compreesed out if it

MYSQL_ROOT_PASSWD=$1

mysqldump -u root "$MYSQL_ROOT_PASSWD" --all-databases > backup.sql

CURRENT_DATE=$(date +"%d-%m-%Y")

tar -czvf "$CURRENT_DATE.tar.gz" backup.sql
