#!/usr/bin/env bash
# loop to 20 with the given conditons
str0="bad luck from China"
str1="bad luck from Japan"
str2="bad luck from Italy"
i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "$str0"
			;;
		9)
			echo "$i"
			echo "$str1"
			;;
		17)
			echo "$i"
			echo "$str2"
			;;
		*)
			echo "$i"
	esac
	((i++))
done
