#!/usr/bin/env bash
# This script configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i '/^127.0.0.1/s/$/ 127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts.new
