#!/usr/bin/env bash
# Run Nginx as Nginx USER

pkill -f apache2
useradd -r -d /var/www -s /sbin/nologin nginx 2>/dev/null
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/www /var/log/nginx /var/run/nginx.pid
sudo -u nginx service nginx start
